### ISSUE TITLE
Setup automated unit tests

### ISSUE THREAD

**Issue by K1ngmar** [rvan-mee/play-man#3]
## Todo
- [X] Choose a unit test framework
  - We went for Cmake
- [X] Setup a basic unit testing project
- [X] Run the tests automatically when a pullrequest is created/updated
  - [X] Make sure that it is required for pullrequests to have the tests pass
  - [X] Run the tests on multiple operating systems
    - [X] linux
    - [X] windows
    - [X] mac
- [X] Setup dockerfiles so we can easily build and run the program/unit tests on different operating systems locally 
  - This works fine for linux, i did set it up for macos too (be it not very efficient, as you need to do a fresh install of macos). As for windows I could not figure how to pull their docker image (will make a seperate issue for this)

**Comment by K1ngmar** [comment]
Fixed in #9
